#define SET_RES_OPTION 8
#define WIDTH_MAX 1920
#define HEIGHT_MAX 1080

#if SET_RES_OPTION==1

#define TILE_WIDTH_MAX 21
#define TILE_HEIGHT_MAX 16
#define START_WIDTH 640
#define START_HEIGHT 480

#elif SET_RES_OPTION==2

#define TILE_WIDTH_MAX 26
#define TILE_HEIGHT_MAX 20
#define START_WIDTH 800
#define START_HEIGHT 608

#elif SET_RES_OPTION==3

#define TILE_WIDTH_MAX 31
#define TILE_HEIGHT_MAX 24
#define START_WIDTH 960
#define START_HEIGHT 736

#elif SET_RES_OPTION==4

#define TILE_WIDTH_MAX 33
#define TILE_HEIGHT_MAX 23
#define START_WIDTH 1024
#define START_HEIGHT 720

#elif SET_RES_OPTION==5

#define TILE_WIDTH_MAX 35
#define TILE_HEIGHT_MAX 20
#define START_WIDTH 1088
#define START_HEIGHT 608

#elif SET_RES_OPTION==6

#define TILE_WIDTH_MAX 41
#define TILE_HEIGHT_MAX 25
#define START_WIDTH 1280
#define START_HEIGHT 768

#elif SET_RES_OPTION==7

#define TILE_WIDTH_MAX 53
#define TILE_HEIGHT_MAX 33
#define START_WIDTH 1680
#define START_HEIGHT 1050

#elif SET_RES_OPTION==8

#define TILE_WIDTH_MAX 61
#define TILE_HEIGHT_MAX 34
#define START_WIDTH 1920
#define START_HEIGHT 1080

#endif
